from .base import Tool, ToolRegistry
from .multi_agents import (
    CheckAgentTool,
    CloseAgentTool,
    ListAgentsTool,
    ResumeAgentTool,
    SendInputTool,
    SpawnAgentTool,
    WaitTool,
)
from .shell import ShellTool
from .files import ReadFileTool, WriteFileTool, GlobTool, GrepTool, ListDirTool, MultiEditTool
from .plan import WritePlanTool
from .claude import BashTool, EditTool, LSTool, ReadTool, WriteTool
from .data import ReadFormatTool, ReadDataTool
from .gemini import (
    GeminiActivateSkillTool,
    GeminiAskUserTool,
    GeminiEnterPlanModeTool,
    GeminiExitPlanModeTool,
    GeminiGetInternalDocsTool,
    GeminiGlobTool,
    GeminiGrepTool,
    GeminiListDirTool,
    GeminiReadFileTool,
    GeminiReadManyFilesTool,
    GeminiReplaceTool,
    GeminiSaveMemoryTool,
    GeminiShellTool,
    GeminiWebFetchTool,
    GeminiWebSearchTool,
    GeminiWriteTodosTool,
)
from .qwen import (
    QwenEditTool,
    QwenGlobTool,
    QwenGrepTool,
    QwenListDirTool,
    QwenLspTool,
    QwenReadFileTool,
    QwenSaveMemoryTool,
    QwenShellTool,
    QwenSkillTool,
    QwenTaskTool,
    QwenTodoWriteTool,
    QwenWebFetchTool,
    QwenWebSearchTool,
)
from .opencode import (
    OpencodeApplyPatchTool,
    OpencodeBashTool,
    OpencodeBatchTool,
    OpencodeCodeSearchTool,
    OpencodeEditTool,
    OpencodeGlobTool,
    OpencodeGrepTool,
    OpencodeListTool,
    OpencodeLspTool,
    OpencodeMultiEditTool,
    OpencodePlanExitTool,
    OpencodeQuestionTool,
    OpencodeReadTool,
    OpencodeSkillTool,
    OpencodeTaskTool,
    OpencodeTodoReadTool,
    OpencodeTodoWriteTool,
    OpencodeWebFetchTool,
    OpencodeWebSearchTool,
    OpencodeWriteTool,
)

__all__ = [
    "Tool",
    "ToolRegistry",
    # default / generic
    "ShellTool",
    "ReadFileTool",
    "WriteFileTool",
    "GlobTool",
    "GrepTool",
    "ListDirTool",
    "MultiEditTool",
    "WritePlanTool",
    # data
    "ReadFormatTool",
    "ReadDataTool",
    # claude
    "BashTool",
    "EditTool",
    "LSTool",
    "ReadTool",
    "WriteTool",
    "GeminiActivateSkillTool",
    "GeminiAskUserTool",
    "GeminiEnterPlanModeTool",
    "GeminiExitPlanModeTool",
    "GeminiGetInternalDocsTool",
    "GeminiGlobTool",
    "GeminiGrepTool",
    "GeminiListDirTool",
    "GeminiReadFileTool",
    "GeminiReadManyFilesTool",
    "GeminiReplaceTool",
    "GeminiSaveMemoryTool",
    "GeminiShellTool",
    "GeminiWebFetchTool",
    "GeminiWebSearchTool",
    "GeminiWriteTodosTool",
    "QwenEditTool",
    "QwenGlobTool",
    "QwenGrepTool",
    "QwenListDirTool",
    "QwenLspTool",
    "QwenReadFileTool",
    "QwenSaveMemoryTool",
    "QwenShellTool",
    "QwenSkillTool",
    "QwenTaskTool",
    "QwenTodoWriteTool",
    "QwenWebFetchTool",
    "QwenWebSearchTool",
    "OpencodeApplyPatchTool",
    "OpencodeBashTool",
    "OpencodeBatchTool",
    "OpencodeCodeSearchTool",
    "OpencodeEditTool",
    "OpencodeGlobTool",
    "OpencodeGrepTool",
    "OpencodeListTool",
    "OpencodeLspTool",
    "OpencodeMultiEditTool",
    "OpencodePlanExitTool",
    "OpencodeQuestionTool",
    "OpencodeReadTool",
    "OpencodeSkillTool",
    "OpencodeTaskTool",
    "OpencodeTodoReadTool",
    "OpencodeTodoWriteTool",
    "OpencodeWebFetchTool",
    "OpencodeWebSearchTool",
    "OpencodeWriteTool",
    # multi-agent
    "SpawnAgentTool",
    "SendInputTool",
    "WaitTool",
    "CloseAgentTool",
    "ResumeAgentTool",
    "ListAgentsTool",
    "CheckAgentTool",
]


def default_registry() -> ToolRegistry:
    """Return a ToolRegistry pre-loaded with all built-in tools."""
    registry = ToolRegistry()
    registry.register(
        ShellTool(),
        ReadFileTool(),
        WriteFileTool(),
        GlobTool(),
        GrepTool(),
        ListDirTool(),
        MultiEditTool(),
    )
    return registry
